# LGM Beginner Level Task - 1 by NEHA NIHARIKA KAR

## Iris Flowers Classification using Supervised Machine Learning

In [1]:
# importing the required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

### Importing and Analysing the Dataset

In [2]:
# importing the dataset from sklearn library
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
print("Target names: {}".format(iris['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


In [4]:
print("Column names: {}".format(iris['feature_names']))

Column names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
print("Type of data: {}".format(type(iris['data'])))

Type of data: <class 'numpy.ndarray'>


In [6]:
print("Shape of dataset: {}".format(iris['data'].shape))

Shape of dataset: (150, 4)


In [7]:
print("Type of target: {}".format(type(iris['target'])))

Type of target: <class 'numpy.ndarray'>


In [8]:
print("Shape of target: {}".format(iris['target'].shape))

Shape of target: (150,)


In [9]:
# representing the dataset in a tabular form
iris_df = pd.DataFrame(np.c_[iris['data'], iris['target']], columns = np.append(iris['feature_names'], ['target']))
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

Target 0 represents Setosa species.

Target 1 represents Versicolor species.

Target 2 represents Virginica species.

### Training and Testing the Data

In [10]:
# splitting the data in the ratio of 70:30
x_train, x_test, y_train, y_test = train_test_split(iris['data'], iris['target'], test_size=0.3, random_state=0)

In [11]:
x_train.shape

(105, 4)

In [12]:
y_train.shape

(105,)

In [13]:
x_test.shape

(45, 4)

In [14]:
y_test.shape

(45,)

In [15]:
# creating K Nearest Neighbors classification model
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [16]:
# making the predictions array
y_pred = knn.predict(x_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [17]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0])

### Testing the Model 

In [18]:
print("Testing dataset accuracy score: {:.3f}".format(knn.score(x_test, y_test)))

Testing dataset accuracy score: 0.978


In [19]:
confusion_matrix(y_test, y_pred)

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)

In [20]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



### Predictions

In [21]:
x_new = np.array([[5, 2.9, 1, 0.2]])
prediction = knn.predict(x_new)
print("Prediction: {}".format(prediction))
print("Predicted class: {}".format(iris['target_names'][prediction]))

Prediction: [0]
Predicted class: ['setosa']


In [22]:
x_new = np.array([[4, 0.9, 0.5, 5.2]])
prediction = knn.predict(x_new)
print("Prediction: {}".format(prediction))
print("Predicted class: {}".format(iris['target_names'][prediction]))

Prediction: [1]
Predicted class: ['versicolor']


In [23]:
x_new = np.array([[2, 2.9, 6, 3.2]])
prediction = knn.predict(x_new)
print("Prediction: {}".format(prediction))
print("Predicted class: {}".format(iris['target_names'][prediction]))

Prediction: [2]
Predicted class: ['virginica']
